services:
  - type: web
    name: cinenova-api
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: GoogleCloud__ProjectId
        sync: false
      - key: GoogleCloud__Location
        value: us-central1
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: MovieApi
      - key: Jwt__Audience
        value: MovieApiUsers
      - key: SendGridSettings__ApiKey
        sync: false
      - key: SendGridSettings__FromEmail
        sync: false
      - key: SendGridSettings__FromName
        value: Soporte CineNova
      - key: Supabase__Url
        sync: false
      - key: Supabase__Key
        sync: false
    secretFiles:
      - key: google-credentials.json
        path: google-credentials.json
